version: '3.8'

services:
  database:
    container_name: mysql_database
    image: mysql:8.0
    volumes:
      - "./.data/mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}

  django:
    container_name: django-server
    build: ${DJANGO_APP_PATH}
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ${DJANGO_APP_PATH}:/app
    ports:
      - "8000:8000"
    depends_on:
      - database
    env_file:
      - .env

  php_my_admin:
    container_name: php_my_admin
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: ${PMA_PORT}
      PMA_ARBITRARY: ${PMA_ARBITRARY}

#  nginx:
#    container_name: nginx
#    image: nginx
#    restart: always
#    build: ./nginx
#    volumes:
#      - ./logs/nginx/:/logs/nginx
#      - ${FRONT_APP_PATH}:/front
#    ports:
#      - "80:80"
#    depends_on:
#      - django
#    environment:
#      NGINX_HOST: ${NGINX_HOST}
#      NGINX_PORT: ${NGINX_PORT}
